using UnityEngine;
using UnityEditor;

/// <summary>
/// Documentation and helper for the Unity Editor internal warning about HttpServerEditorWrapper.
/// 
/// This is a known Unity bug (UUM-53673) that Unity has marked as "Won't Fix".
/// The warning is completely harmless and does NOT affect your builds or game functionality.
/// 
/// SOLUTIONS:
/// 1. IGNORE IT (Recommended) - It's just noise, your builds work fine
/// 2. Filter in Console - Right-click the warning > "Filter by this text" > Hide matching messages
/// 3. Clear Console - The warning only appears during WebGL builds, clear console after building
/// 
/// This script serves as documentation. The warning cannot be programmatically suppressed
/// because it's generated by Unity's internal code before any user scripts can intercept it.
/// </summary>
[InitializeOnLoad]
public static class SuppressWebGLWarning
{
    static SuppressWebGLWarning()
    {
        // This script exists to document the issue
        // Unity's internal warning system doesn't allow programmatic suppression
        // of warnings generated by Unity's own code
    }
}
