using UnityEngine;
using System;
using System.Collections.Generic;

/// <summary>
/// Types of spontaneous interactions that ML-Agents can generate.
/// These add unpredictability and realism to classroom simulation.
/// </summary>
public enum InteractionType
{
    /// <summary>Concise question about the lesson content</summary>
    Question,

    /// <summary>Expression of misunderstanding or confusion</summary>
    Confusion,

    /// <summary>Natural interruption (unrelated to lesson)</summary>
    Interruption,

    /// <summary>Social chatter with nearby peers</summary>
    SocialChatter,

    /// <summary>Comment or observation about the lesson</summary>
    Comment,

    /// <summary>Request for help or clarification</summary>
    HelpRequest,

    /// <summary>Spontaneous answer attempt (calling out)</summary>
    CallOut
}

/// <summary>
/// Priority level for interactions - determines urgency and visual prominence
/// </summary>
public enum InteractionPriority
{
    Low,        // Background chatter, can be ignored
    Medium,     // Normal questions, confusion
    High,       // Important interruptions, distress
    Urgent      // Critical situations requiring immediate attention
}

/// <summary>
/// Represents a spontaneous verbal interaction generated by ML-Agents.
/// Contains all context needed for display and teacher response.
/// </summary>
[Serializable]
public class SpontaneousInteraction
{
    /// <summary>Unique identifier for tracking</summary>
    public string interactionId;

    /// <summary>ID of the student generating the interaction</summary>
    public string studentId;

    /// <summary>Name of the student for display</summary>
    public string studentName;

    /// <summary>Type of interaction</summary>
    public InteractionType type;

    /// <summary>Priority level</summary>
    public InteractionPriority priority;

    /// <summary>The verbal content/text of the interaction</summary>
    public string content;

    /// <summary>Optional target student ID (for social chatter)</summary>
    public string targetStudentId;

    /// <summary>Timestamp when interaction was generated</summary>
    public float timestamp;

    /// <summary>Duration to display the interaction (seconds)</summary>
    public float displayDuration;

    /// <summary>Whether this interaction requires teacher response</summary>
    public bool requiresResponse;

    /// <summary>Emotional context that triggered this interaction</summary>
    public EmotionalContext emotionalContext;

    /// <summary>Confidence score from ML model (0-1)</summary>
    public float confidence;

    /// <summary>
    /// Create a new spontaneous interaction
    /// </summary>
    public SpontaneousInteraction(
        string studentId,
        string studentName,
        InteractionType type,
        string content,
        InteractionPriority priority = InteractionPriority.Medium)
    {
        this.interactionId = Guid.NewGuid().ToString();
        this.studentId = studentId;
        this.studentName = studentName;
        this.type = type;
        this.content = content;
        this.priority = priority;
        this.timestamp = Time.time;
        this.displayDuration = GetDefaultDuration(type);
        this.requiresResponse = ShouldRequireResponse(type);
        this.confidence = 1f;
    }

    /// <summary>
    /// Get default display duration based on interaction type
    /// </summary>
    private static float GetDefaultDuration(InteractionType type)
    {
        switch (type)
        {
            case InteractionType.Question:
                return 8f;
            case InteractionType.Confusion:
                return 6f;
            case InteractionType.Interruption:
                return 5f;
            case InteractionType.SocialChatter:
                return 4f;
            case InteractionType.Comment:
                return 5f;
            case InteractionType.HelpRequest:
                return 7f;
            case InteractionType.CallOut:
                return 4f;
            default:
                return 5f;
        }
    }

    /// <summary>
    /// Determine if interaction type typically requires teacher response
    /// </summary>
    private static bool ShouldRequireResponse(InteractionType type)
    {
        switch (type)
        {
            case InteractionType.Question:
            case InteractionType.Confusion:
            case InteractionType.HelpRequest:
                return true;
            case InteractionType.Interruption:
            case InteractionType.SocialChatter:
            case InteractionType.Comment:
            case InteractionType.CallOut:
                return false;
            default:
                return false;
        }
    }

    /// <summary>
    /// Get icon/emoji representation for UI display
    /// </summary>
    public string GetTypeIcon()
    {
        switch (type)
        {
            case InteractionType.Question: return "?";
            case InteractionType.Confusion: return "??";
            case InteractionType.Interruption: return "!";
            case InteractionType.SocialChatter: return "...";
            case InteractionType.Comment: return "*";
            case InteractionType.HelpRequest: return "SOS";
            case InteractionType.CallOut: return "!";
            default: return "";
        }
    }

    /// <summary>
    /// Get Hebrew label for interaction type
    /// </summary>
    public string GetTypeLabel()
    {
        switch (type)
        {
            case InteractionType.Question: return "שאלה";
            case InteractionType.Confusion: return "בלבול";
            case InteractionType.Interruption: return "הפרעה";
            case InteractionType.SocialChatter: return "שיחה";
            case InteractionType.Comment: return "הערה";
            case InteractionType.HelpRequest: return "עזרה";
            case InteractionType.CallOut: return "קריאה";
            default: return "";
        }
    }
}

/// <summary>
/// Emotional context snapshot at the time of interaction generation
/// </summary>
[Serializable]
public class EmotionalContext
{
    public float happiness;
    public float sadness;
    public float frustration;
    public float boredom;
    public float anger;
    public StudentState currentState;

    /// <summary>
    /// Create from EmotionVector and StudentState
    /// </summary>
    public static EmotionalContext FromStudent(EmotionVector emotions, StudentState state)
    {
        return new EmotionalContext
        {
            happiness = emotions.Happiness,
            sadness = emotions.Sadness,
            frustration = emotions.Frustration,
            boredom = emotions.Boredom,
            anger = emotions.Anger,
            currentState = state
        };
    }

    /// <summary>
    /// Get dominant emotion name
    /// </summary>
    public string GetDominantEmotion()
    {
        float max = Mathf.Max(happiness, Mathf.Max(sadness, Mathf.Max(frustration, Mathf.Max(boredom, anger))));
        if (max == happiness) return "happiness";
        if (max == sadness) return "sadness";
        if (max == frustration) return "frustration";
        if (max == boredom) return "boredom";
        return "anger";
    }
}

/// <summary>
/// Request payload for ML-Agent interaction generation API
/// </summary>
[Serializable]
public class InteractionGenerationRequest
{
    public string studentId;
    public string studentName;
    public StudentProfileData profile;
    public EmotionalContext emotions;
    public ClassroomContextData classroomContext;
    public List<string> enabledInteractionTypes;
    public float temperature;
    public int maxTokens;

    /// <summary>
    /// Student profile data for ML model context
    /// </summary>
    [Serializable]
    public class StudentProfileData
    {
        public float extroversion;
        public float sensitivity;
        public float rebelliousness;
        public float academicMotivation;
    }

    /// <summary>
    /// Classroom context data for ML model
    /// </summary>
    [Serializable]
    public class ClassroomContextData
    {
        public string currentLessonTopic;
        public float lessonProgress;
        public int totalStudents;
        public float classAverageEngagement;
        public List<NearbyStudentData> nearbyStudents;
        public float timeSinceLastTeacherAction;
        public string lastTeacherActionType;
    }

    /// <summary>
    /// Data about nearby students for social context
    /// </summary>
    [Serializable]
    public class NearbyStudentData
    {
        public string studentId;
        public string studentName;
        public StudentState currentState;
        public float distance;
    }
}

/// <summary>
/// Response from ML-Agent interaction generation API
/// </summary>
[Serializable]
public class InteractionGenerationResponse
{
    public bool success;
    public string error;
    public InteractionResult result;

    [Serializable]
    public class InteractionResult
    {
        public string interactionType;
        public string content;
        public string priority;
        public float confidence;
        public string targetStudentId;
        public bool requiresResponse;
    }
}

/// <summary>
/// Collection of pre-defined interaction templates for fallback generation
/// </summary>
public static class InteractionTemplates
{
    // Question templates (Hebrew)
    public static readonly string[] QuestionTemplatesHebrew = new[]
    {
        "המורה, אפשר לשאול שאלה?",
        "לא הבנתי, אפשר להסביר שוב?",
        "מה זה אומר?",
        "למה זה ככה?",
        "איך עושים את זה?",
        "מה עושים עכשיו?",
        "זה יהיה במבחן?",
        "אפשר דוגמה?",
        "מה הקשר לנושא הקודם?",
        "אני לא מבין את השלב הזה"
    };

    // Confusion templates (Hebrew)
    public static readonly string[] ConfusionTemplatesHebrew = new[]
    {
        "רגע, מה?",
        "אני מבולבל...",
        "לא הבנתי כלום",
        "זה מסובך מדי",
        "הלכתי לאיבוד",
        "אני לא עוקב",
        "מה קרה פה?",
        "חכה, מה עכשיו?",
        "אני לא מצליח להבין",
        "זה עבר לי מעל הראש"
    };

    // Interruption templates (Hebrew)
    public static readonly string[] InterruptionTemplatesHebrew = new[]
    {
        "אפשר לצאת לשירותים?",
        "מתי ההפסקה?",
        "אני צמא",
        "חם פה",
        "קר לי",
        "אפשר לפתוח חלון?",
        "שכחתי את המחברת",
        "אין לי עט",
        "מתי נגמר השיעור?",
        "יש לי כאב ראש"
    };

    // Social chatter templates (Hebrew)
    public static readonly string[] SocialChatterTemplatesHebrew = new[]
    {
        "פסססט...",
        "ראית את זה?",
        "משעמם...",
        "מה עשית אתמול?",
        "תביא לי גומי",
        "תסתכל על זה",
        "הי, תקשיב",
        "מה יש לך להפסקה?",
        "באת לאימון היום?",
        "שמעת על..."
    };

    // Comment templates (Hebrew)
    public static readonly string[] CommentTemplatesHebrew = new[]
    {
        "זה מעניין!",
        "וואו, לא ידעתי",
        "זה כמו...",
        "אני מכיר את זה!",
        "למדנו את זה בשנה שעברה",
        "זה קשור ל...",
        "אח שלי אמר ש...",
        "ראיתי את זה בטלוויזיה",
        "זה מזכיר לי משהו",
        "מגניב!"
    };

    // Help request templates (Hebrew)
    public static readonly string[] HelpRequestTemplatesHebrew = new[]
    {
        "המורה, אני צריך עזרה",
        "אני תקוע",
        "אני לא מצליח",
        "אפשר לגשת אלי?",
        "יש לי בעיה",
        "לא יודע מה לעשות",
        "המורה, תעזור לי",
        "אני לא מסתדר עם זה",
        "צריך עזרה פה",
        "אני לא מבין מה לעשות"
    };

    // Call out templates (Hebrew)
    public static readonly string[] CallOutTemplatesHebrew = new[]
    {
        "אני יודע!",
        "התשובה היא...",
        "זה קל!",
        "אני!",
        "ברור!",
        "פשוט!",
        "יודע יודע!",
        "הבנתי!",
        "זה...",
        "נראה לי ש..."
    };

    /// <summary>
    /// Get random template for interaction type
    /// </summary>
    public static string GetRandomTemplate(InteractionType type)
    {
        string[] templates = GetTemplatesForType(type);
        if (templates != null && templates.Length > 0)
        {
            return templates[UnityEngine.Random.Range(0, templates.Length)];
        }
        return "";
    }

    /// <summary>
    /// Get all templates for a specific interaction type
    /// </summary>
    public static string[] GetTemplatesForType(InteractionType type)
    {
        switch (type)
        {
            case InteractionType.Question:
                return QuestionTemplatesHebrew;
            case InteractionType.Confusion:
                return ConfusionTemplatesHebrew;
            case InteractionType.Interruption:
                return InterruptionTemplatesHebrew;
            case InteractionType.SocialChatter:
                return SocialChatterTemplatesHebrew;
            case InteractionType.Comment:
                return CommentTemplatesHebrew;
            case InteractionType.HelpRequest:
                return HelpRequestTemplatesHebrew;
            case InteractionType.CallOut:
                return CallOutTemplatesHebrew;
            default:
                return null;
        }
    }
}
